services:
  db:
    image: postgres:17.4-alpine
    container_name: nexus_pg_db
    env_file: app/.env
    ports:
      - "5432:5432"
    networks:
      - nexus_network

  nexus_app:
    build: .
    container_name: nexus_app
    depends_on:
      - db
    env_file:
      - app/.env
    ports:
      - "8000:8000"
    networks:
      - nexus_network
    command: sh -c "poetry run alembic upgrade head \           
              && psql -f initdb.sql \                           
              && poetry run python main.py"


networks:
  nexus_network:
    name: nexus_network
    driver: bridge